# Generated by Django 3.0.3 on 2020-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=200)),
                ('picture', models.ImageField(upload_to='event_posters')),
                ('rules', models.TextField(max_length=1500)),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
