# Generated by Django 3.0.3 on 2020-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_events_select_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
