# Generated by Django 3.0.3 on 2020-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cost',
            field=models.CharField(default='100', max_length=4),
        ),
        migrations.AddField(
            model_name='registration',
            name='mi_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='participant_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_timestamp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
