# Generated by Django 3.0.3 on 2020-08-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200825_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='select_state',
            field=models.CharField(choices=[('West Bengal', 'West bengal'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Odisha', 'Odisha'), ('Tamil Nadu', 'Tamil Nadu')], default=1, max_length=50),
        ),
    ]
