# Generated by Django 3.0.3 on 2020-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200825_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='total_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
