# Generated by Django 3.0.3 on 2020-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200825_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
