# Generated by Django 3.0.3 on 2020-08-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200826_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_timestamp',
        ),
    ]
