# Generated by Django 3.0.3 on 2020-08-26 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_registration_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 17, 56, 43, 737011)),
        ),
    ]
