# Generated by Django 3.0.3 on 2020-08-26 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_registration_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 14, 31, 636881)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 14, 31, 635881)),
        ),
    ]
