# Generated by Django 3.0.3 on 2020-08-26 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20200826_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 22, 58, 38, 595443)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 58, 38, 598439)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 58, 38, 598438)),
        ),
        migrations.CreateModel(
            name='date_revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('revenue', models.IntegerField()),
                ('no_of_participants', models.IntegerField()),
                ('event_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.events')),
            ],
        ),
    ]
