# Generated by Django 3.0.3 on 2020-08-28 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20200827_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('state_connected_to', models.CharField(choices=[('West Bengal', 'West bengal'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Odisha', 'Odisha'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 8, 22, 0, 31, 49, 923923)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 29, 0, 31, 49, 925907)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 29, 0, 31, 49, 925906)),
        ),
    ]
