# Generated by Django 3.0.3 on 2020-09-03 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20200829_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='email',
            field=models.EmailField(default='prodigygamer143@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='password',
            field=models.CharField(default='8017586761', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 20, 40, 22, 354014)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 3, 20, 40, 22, 357014)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 3, 20, 40, 22, 357014)),
        ),
    ]
