# Generated by Django 3.0.3 on 2020-09-15 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20200907_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='password',
            field=models.CharField(default='8017586761', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 1, 6, 31, 926930)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 16, 1, 6, 32, 277938)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 19, 36, 32, 277938, tzinfo=utc)),
        ),
    ]
