# Generated by Django 3.0.3 on 2020-09-15 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_auto_20200916_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 1, 8, 14, 765444)),
        ),
        migrations.AlterField(
            model_name='events',
            name='summary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 16, 1, 8, 15, 79434)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 19, 38, 15, 79434, tzinfo=utc)),
        ),
    ]
