# Generated by Django 3.0.3 on 2020-09-15 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_auto_20200916_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 19, 53, 44, 37900)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 15, 19, 53, 44, 52956)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 19, 53, 44, 52865, tzinfo=utc)),
        ),
    ]
