# Generated by Django 3.0.3 on 2020-09-16 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_auto_20200916_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referral',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 20, 27, 13, 186519)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 27, 13, 728513)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 14, 57, 13, 728512, tzinfo=utc)),
        ),
    ]
