# Generated by Django 3.0.3 on 2020-09-16 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20200916_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cost2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 20, 56, 56, 705152)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 56, 57, 330105)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 15, 26, 57, 330104, tzinfo=utc)),
        ),
    ]
