# Generated by Django 3.0.3 on 2020-09-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20200916_2056'),
        ('firstapp', '0021_auto_20200915_1953'),
    ]

    operations = [
    ]
