# Generated by Django 3.0.3 on 2020-09-16 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_merge_20200917_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cluster',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 0, 18, 48, 430409)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 17, 0, 18, 49, 77399)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 18, 48, 49, 77398, tzinfo=utc)),
        ),
    ]
