# Generated by Django 3.0.3 on 2020-09-16 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_auto_20200917_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 2, 3, 20, 498120)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 17, 2, 3, 21, 192111)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 33, 21, 192111, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_amount', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.events')),
            ],
        ),
    ]
