# Generated by Django 3.0.3 on 2020-09-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_merge_20200916_1830'),
        ('firstapp', '0026_auto_20200917_0203'),
    ]

    operations = [
    ]
