# Generated by Django 3.0.3 on 2020-09-17 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_merge_20200916_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='mi_id',
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 8, 53, 0, 619811)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 17, 8, 53, 0, 633604)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 17, 8, 53, 0, 633543, tzinfo=utc)),
        ),
    ]
