# Generated by Django 3.0.3 on 2020-10-28 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_auto_20200917_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='payment_script',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 4, 29, 51, 342765)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_registered',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 28, 4, 29, 51, 361651)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 28, 4, 29, 51, 361587, tzinfo=utc)),
        ),
    ]
