# Generated by Django 3.0.3 on 2020-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_auto_20201116_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='select_state',
            field=models.CharField(default='Depreciated Field... Not Required', max_length=50),
        ),
    ]
