# Generated by Django 3.0.3 on 2021-10-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_auto_20210923_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='events',
            name='select_state',
        ),
        migrations.RemoveField(
            model_name='events',
            name='state',
        ),
        migrations.AddField(
            model_name='events',
            name='cost3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Category'),
        ),
    ]
